/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmlamportsignature_free: (a: number, b: number) => void;
export const __wbg_wasmratchetsession_free: (a: number, b: number) => void;
export const __wbg_wasmshield_free: (a: number, b: number) => void;
export const __wbg_wasmtotp_free: (a: number, b: number) => void;
export const constantTimeEquals: (a: number, b: number, c: number, d: number) => number;
export const hmacSha256: (a: number, b: number, c: number, d: number) => [number, number];
export const quickDecrypt: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const quickEncrypt: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const randomBytes: (a: number) => [number, number, number, number];
export const sha256: (a: number, b: number) => [number, number];
export const wasmlamportsignature_fingerprint: (a: number) => [number, number];
export const wasmlamportsignature_isUsed: (a: number) => number;
export const wasmlamportsignature_new: () => [number, number, number];
export const wasmlamportsignature_publicKey: (a: number) => [number, number];
export const wasmlamportsignature_sign: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmlamportsignature_verifySignature: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const wasmratchetsession_decrypt: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmratchetsession_encrypt: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmratchetsession_new: (a: number, b: number, c: number) => [number, number, number];
export const wasmratchetsession_recvCounter: (a: number) => bigint;
export const wasmratchetsession_sendCounter: (a: number) => bigint;
export const wasmshield_decrypt: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmshield_encrypt: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmshield_key: (a: number) => [number, number];
export const wasmshield_new: (a: number, b: number, c: number, d: number) => number;
export const wasmshield_withKey: (a: number, b: number) => [number, number, number];
export const wasmtotp_fromBase32: (a: number, b: number) => [number, number, number, number];
export const wasmtotp_generate: (a: number, b: bigint) => [number, number];
export const wasmtotp_generateNow: (a: number) => [number, number];
export const wasmtotp_generateSecret: () => [number, number, number, number];
export const wasmtotp_new: (a: number, b: number) => number;
export const wasmtotp_provisioningUri: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmtotp_toBase32: (a: number) => [number, number];
export const wasmtotp_verify: (a: number, b: number, c: number, d: bigint, e: number) => number;
export const wasmtotp_verifyNow: (a: number, b: number, c: number, d: number) => number;
export const wasmtotp_withSettings: (a: number, b: number, c: number, d: bigint) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
