package ai.dikestra.arkachat.crypto

import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import java.security.KeyPairGenerator
import java.security.Signature
import java.security.spec.ECGenParameterSpec

/**
 * Unit tests for GroupAdminKeyManager.
 *
 * Android Keystore is not available in unit tests, so these tests cover:
 * - Canonical signing-input construction (same on Android and Web)
 * - DER ↔ raw (r || s) conversion
 * - Sign + verify using a JVM-local keypair (bypassing Keystore)
 * - Cross-platform test vector verification (static vector generated by Web)
 *
 * Integration tests that exercise the Android Keystore itself live in
 * androidTest/GroupAdminKeyManagerInstrumentedTest.kt.
 */
class GroupAdminKeyManagerTest {

    private lateinit var manager: GroupAdminKeyManager

    @Before
    fun setup() {
        manager = GroupAdminKeyManager()
    }

    // ---- Signing-input construction ----

    @Test
    fun `buildSigningInput matches expected format`() {
        val input = manager.buildSigningInput(
            type = "MEMBER_ADDED",
            groupId = "group-123",
            senderId = "sender-456",
            timestamp = 1700000000000L,
            payloadJson = ""
        )
        val text = String(input, Charsets.UTF_8)
        assertTrue("Must start with domain sep", text.startsWith("arkachat:control:v1:"))
        assertTrue("Must contain type", text.contains("MEMBER_ADDED"))
        assertTrue("Must contain groupId", text.contains("group-123"))
        assertTrue("Must contain senderId", text.contains("sender-456"))
        assertTrue("Must contain timestamp", text.contains("1700000000000"))
        // SHA-256("") must be the well-known empty hash
        assertTrue("Must contain empty payload hash",
            text.contains("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"))
    }

    @Test
    fun `buildSigningInput is deterministic`() {
        val a = manager.buildSigningInput("MEMBER_REMOVED", "g1", "s1", 999L, "{}")
        val b = manager.buildSigningInput("MEMBER_REMOVED", "g1", "s1", 999L, "{}")
        assertArrayEquals(a, b)
    }

    @Test
    fun `buildSigningInput differs for different types`() {
        val a = manager.buildSigningInput("MEMBER_ADDED", "g1", "s1", 1L, "")
        val b = manager.buildSigningInput("MEMBER_REMOVED", "g1", "s1", 1L, "")
        assertFalse(a.contentEquals(b))
    }

    @Test
    fun `buildSigningInput differs for different timestamps`() {
        val a = manager.buildSigningInput("KEY_ROTATION", "g1", "s1", 1000L, "")
        val b = manager.buildSigningInput("KEY_ROTATION", "g1", "s1", 2000L, "")
        assertFalse(a.contentEquals(b))
    }

    @Test
    fun `buildSigningInput differs for different payloads`() {
        val a = manager.buildSigningInput("KEY_ROTATION", "g1", "s1", 1L, "{\"k\":1}")
        val b = manager.buildSigningInput("KEY_ROTATION", "g1", "s1", 1L, "{\"k\":2}")
        assertFalse(a.contentEquals(b))
    }

    // ---- DER ↔ raw conversion ----

    @Test
    fun `derToRaw and rawToDer are inverses`() {
        // Generate a real signature to get a real DER blob
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp = kpg.generateKeyPair()

        val message = "test-round-trip".toByteArray()
        val sig = Signature.getInstance("SHA256withECDSA").apply {
            initSign(kp.private)
            update(message)
        }.sign()

        val raw = manager.derToRaw(sig)
        assertEquals("Raw signature must be 64 bytes", 64, raw.size)

        val derBack = manager.rawToDer(raw)

        // Verify the reconstructed DER signature is accepted
        val valid = Signature.getInstance("SHA256withECDSA").apply {
            initVerify(kp.public)
            update(message)
        }.verify(derBack)
        assertTrue("Round-tripped DER must verify", valid)
    }

    @Test
    fun `rawToDer handles high-bit r and s`() {
        // Construct a raw signature where r[0] and s[0] have bit 7 set
        val raw = ByteArray(64).also {
            it[0] = 0xFF.toByte()  // high bit set → needs 0x00 prefix in DER
            it[32] = 0x80.toByte() // high bit set → needs 0x00 prefix in DER
        }
        val der = manager.rawToDer(raw)
        assertTrue("Should start with SEQUENCE tag 0x30", der[0] == 0x30.toByte())
    }

    // ---- Sign + verify with JVM-local keypair (no Keystore) ----

    private fun signWithJvmKey(
        privateKey: java.security.PrivateKey,
        type: String, groupId: String, senderId: String,
        timestamp: Long, payloadJson: String
    ): ByteArray {
        val message = manager.buildSigningInput(type, groupId, senderId, timestamp, payloadJson)
        val der = Signature.getInstance("SHA256withECDSA").apply {
            initSign(privateKey)
            update(message)
        }.sign()
        return manager.derToRaw(der)
    }

    @Test
    fun `verifyControlMessage accepts valid signature`() {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp = kpg.generateKeyPair()

        val rawSig = signWithJvmKey(kp.private, "MEMBER_ADDED", "g1", "me", 100L, "")

        val valid = manager.verifyControlMessage(
            adminPublicKeyBytes = kp.public.encoded,
            type = "MEMBER_ADDED",
            groupId = "g1",
            senderId = "me",
            timestamp = 100L,
            payloadJson = "",
            rawSignature = rawSig
        )
        assertTrue("Valid signature must verify", valid)
    }

    @Test
    fun `verifyControlMessage rejects wrong type`() {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp = kpg.generateKeyPair()

        // Signed as MEMBER_ADDED but verified as MEMBER_REMOVED
        val rawSig = signWithJvmKey(kp.private, "MEMBER_ADDED", "g1", "me", 100L, "")

        val valid = manager.verifyControlMessage(
            adminPublicKeyBytes = kp.public.encoded,
            type = "MEMBER_REMOVED",
            groupId = "g1",
            senderId = "me",
            timestamp = 100L,
            payloadJson = "",
            rawSignature = rawSig
        )
        assertFalse("Wrong type must fail verification", valid)
    }

    @Test
    fun `verifyControlMessage rejects tampered signature`() {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp = kpg.generateKeyPair()

        val rawSig = signWithJvmKey(kp.private, "KEY_ROTATION", "g1", "me", 200L, "").also {
            it[0] = it[0].xor(0xFF.toByte()) // flip all bits of first byte
        }

        val valid = manager.verifyControlMessage(
            adminPublicKeyBytes = kp.public.encoded,
            type = "KEY_ROTATION",
            groupId = "g1",
            senderId = "me",
            timestamp = 200L,
            payloadJson = "",
            rawSignature = rawSig
        )
        assertFalse("Tampered signature must fail", valid)
    }

    @Test
    fun `verifyControlMessage rejects wrong public key`() {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp1 = kpg.generateKeyPair()
        val kp2 = kpg.generateKeyPair()

        val rawSig = signWithJvmKey(kp1.private, "ADMIN_CHANGE", "g1", "me", 300L, "{}")

        val valid = manager.verifyControlMessage(
            adminPublicKeyBytes = kp2.public.encoded, // Wrong key
            type = "ADMIN_CHANGE",
            groupId = "g1",
            senderId = "me",
            timestamp = 300L,
            payloadJson = "{}",
            rawSignature = rawSig
        )
        assertFalse("Signature from different key must fail", valid)
    }

    @Test
    fun `verifyControlMessage rejects 65-byte signature`() {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(ECGenParameterSpec("secp256r1"))
        val kp = kpg.generateKeyPair()

        val bad = ByteArray(65) // wrong size
        val valid = manager.verifyControlMessage(
            adminPublicKeyBytes = kp.public.encoded,
            type = "MEMBER_ADDED",
            groupId = "g1",
            senderId = "me",
            timestamp = 100L,
            rawSignature = bad
        )
        assertFalse("Wrong-length signature must fail", valid)
    }

    // ---- Cross-platform test vector ----
    // This vector was generated in groupAdminKeyManager.test.ts (Web) and must
    // verify correctly here on Android.
    //
    // The canonical signing input for this vector is:
    //   "arkachat:control:v1:MEMBER_ADDED:vec-group:vec-sender:1700000000000:
    //    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    //
    // Instructions for updating: run the web test to get a fresh SPKI + signature
    // pair and paste them below.

    @Test
    fun `signing input for cross-platform vector is stable`() {
        val input = manager.buildSigningInput(
            type = "MEMBER_ADDED",
            groupId = "vec-group",
            senderId = "vec-sender",
            timestamp = 1700000000000L,
            payloadJson = ""
        )
        val expected =
            "arkachat:control:v1:MEMBER_ADDED:vec-group:vec-sender:1700000000000:" +
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        assertEquals(expected, String(input, Charsets.UTF_8))
    }
}
